// Auto-generated by buffers_gen_js.py - do not edit manually.
// Shared support module for wire buffer reading/writing.

export const BUFFERS_SUCCESS = 0;
export const BUFFERS_EOF = -1;
export const BUFFERS_ERROR_EOF = -2;

const _utf8Decoder = new TextDecoder('utf-8');
const _utf8Encoder = new TextEncoder();

// --- UTF-8 (char[]) ---------------------------------------------------------

// Decode up to `max` bytes from u8 at off, stopping at the first NUL byte.
export function decodeUtf8(u8, off, max) {
  let end = off + max;
  for (let i = off; i < off + max; i++) {
    if (u8[i] === 0) { end = i; break; }
  }
  return _utf8Decoder.decode(u8.subarray(off, end));
}

// Encode a string as UTF-8, truncated to at most `cap` bytes on a valid
// code-point boundary (never splits a multibyte sequence). Returns a Uint8Array.
export function encodeUtf8Bounded(value, cap) {
  if (value == null || value.length === 0) return new Uint8Array(0);
  const full = _utf8Encoder.encode(value);
  if (full.length <= cap) return full;
  // Truncate without splitting: back up off any UTF-8 continuation bytes.
  let n = cap;
  while (n > 0 && (full[n] & 0xC0) === 0x80) n--;
  return full.subarray(0, n);
}

// Byte length of encodeUtf8Bounded(value, cap) without allocating the slice.
export function utf8Bounded(value, cap) {
  return encodeUtf8Bounded(value, cap).length;
}

// Encode a string as UTF-8 into a fixed `cap`-byte field at off, zero-padded.
// Truncates on a valid code-point boundary if necessary.
export function encodeUtf8Fixed(value, u8, off, cap) {
  u8.fill(0, off, off + cap);
  if (value == null || value.length === 0) return;
  const enc = encodeUtf8Bounded(value, cap);
  u8.set(enc, off);
}

// --- UTF-16 (wchar_t[]) -----------------------------------------------------

// Number of UTF-16 code units to emit for `value`, capped at `cap`, never
// splitting a surrogate pair at the boundary.
export function utf16Units(value, cap) {
  if (value == null || value.length === 0) return 0;
  let n = Math.min(value.length, cap);
  // If we'd cut between a high and low surrogate, drop the lone high surrogate.
  if (n > 0 && n < value.length) {
    const c = value.charCodeAt(n - 1);
    if (c >= 0xD800 && c <= 0xDBFF) n--;
  }
  return n;
}

// Decode `byteLen` bytes of UTF-16 (LE unless be) at off, stopping at the
// first NUL code unit (0x0000).
export function decodeUtf16(u8, off, byteLen, be) {
  const units = byteLen >> 1;
  let count = units;
  for (let i = 0; i < units; i++) {
    const lo = u8[off + i * 2];
    const hi = u8[off + i * 2 + 1];
    const cu = be ? ((lo << 8) | hi) : ((hi << 8) | lo);
    if (cu === 0) { count = i; break; }
  }
  let s = '';
  for (let i = 0; i < count; i++) {
    const lo = u8[off + i * 2];
    const hi = u8[off + i * 2 + 1];
    const cu = be ? ((lo << 8) | hi) : ((hi << 8) | lo);
    s += String.fromCharCode(cu);
  }
  return s;
}

// Write `units` UTF-16 code units of `value` into u8 at off (LE unless be).
export function encodeUtf16Into(value, units, u8, off, be) {
  for (let i = 0; i < units; i++) {
    const cu = value.charCodeAt(i);
    const hi = (cu >> 8) & 0xFF;
    const lo = cu & 0xFF;
    if (be) { u8[off + i * 2] = hi; u8[off + i * 2 + 1] = lo; }
    else    { u8[off + i * 2] = lo; u8[off + i * 2 + 1] = hi; }
  }
}

// Encode a string as UTF-16 into a fixed `cap`-unit field at off (cap*2 bytes),
// zero-padded, never splitting a surrogate pair.
export function encodeUtf16Fixed(value, u8, off, cap, be) {
  const byteCap = cap * 2;
  u8.fill(0, off, off + byteCap);
  if (value == null || value.length === 0) return;
  const units = utf16Units(value, cap);
  encodeUtf16Into(value, units, u8, off, be);
}
