// Auto-generated by buffers_gen_js.py - do not edit manually.
// Wire format: little-endian, variable-length strings.
import { decodeUtf8, decodeUtf16, encodeUtf8Fixed, encodeUtf16Fixed, encodeUtf8Bounded, utf8Bounded, utf16Units, encodeUtf16Into } from './buffers.js';

export const EXAMPLE_MAX_SIZE = 164;
export const EXAMPLE_COLOR_SIZE = 4;
export const EXAMPLE_VALUE_SIZE = 8;
export const EXAMPLE_VALUES_ENTRY_SIZE = 16;
export const EXAMPLE_DATA_MESSAGE_SIZE = 32;
export const EXAMPLE_SCREEN_VALUE_ENTRY_SIZE = 17;
export const EXAMPLE_SCREEN_ENTRY_SIZE = 71;
export const EXAMPLE_SCREEN_MESSAGE_SIZE = 144;
export const EXAMPLE_NOP_MESSAGE_SIZE = 0;
export const EXAMPLE_CLEAR_MESSAGE_SIZE = 0;
export const EXAMPLE_MODE_MESSAGE_SIZE = 1;
export const EXAMPLE_RESET_SCREEN_MESSAGE_SIZE = 0;
export const EXAMPLE_IDENT_REQUEST_MESSAGE_SIZE = 0;
export const EXAMPLE_IDENT_MESSAGE_SIZE = 164;

export const ExampleMessageCommand = Object.freeze({ CmdNone: 0, CmdData: 1, CmdScreen: 2, CmdNop: 3, CmdClear: 4, CmdMode: 5, CmdResetScreen: 6, CmdIdentRequest: 7, CmdIdent: 8 });
export const ExampleInputType = Object.freeze({ InputNone: 0, InputTouch: 1, InputButton: 2 });

export function exampleColorRead(u8, offset = 0, outBytesRead = null) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  const result = {};
  let off = offset;
  if (off + 1 > u8.byteLength) return null;
  result.a = u8[off];
  off += 1;
  if (off + 1 > u8.byteLength) return null;
  result.r = u8[off];
  off += 1;
  if (off + 1 > u8.byteLength) return null;
  result.g = u8[off];
  off += 1;
  if (off + 1 > u8.byteLength) return null;
  result.b = u8[off];
  off += 1;
  if (outBytesRead) outBytesRead[0] = off - offset;
  return result;
}

export function exampleColorWrite(obj, u8, offset = 0) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  let off = offset;
  if (off + 1 > u8.byteLength) return -1;
  u8[off] = obj.a & 0xFF;
  off += 1;
  if (off + 1 > u8.byteLength) return -1;
  u8[off] = obj.r & 0xFF;
  off += 1;
  if (off + 1 > u8.byteLength) return -1;
  u8[off] = obj.g & 0xFF;
  off += 1;
  if (off + 1 > u8.byteLength) return -1;
  u8[off] = obj.b & 0xFF;
  off += 1;
  return off - offset;
}

export function exampleColorSize(obj) {
  let size = 0;
  size += 1;
  size += 1;
  size += 1;
  size += 1;
  return size;
}

export function exampleValueRead(u8, offset = 0, outBytesRead = null) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  const result = {};
  let off = offset;
  if (off + 4 > u8.byteLength) return null;
  result.value = dv.getFloat32(off, true);
  off += 4;
  if (off + 4 > u8.byteLength) return null;
  result.scaled = dv.getFloat32(off, true);
  off += 4;
  if (outBytesRead) outBytesRead[0] = off - offset;
  return result;
}

export function exampleValueWrite(obj, u8, offset = 0) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  let off = offset;
  if (off + 4 > u8.byteLength) return -1;
  dv.setFloat32(off, obj.value, true);
  off += 4;
  if (off + 4 > u8.byteLength) return -1;
  dv.setFloat32(off, obj.scaled, true);
  off += 4;
  return off - offset;
}

export function exampleValueSize(obj) {
  let size = 0;
  size += 4;
  size += 4;
  return size;
}

export function exampleValuesEntryRead(u8, offset = 0, outBytesRead = null) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  const result = {};
  let off = offset;
  { // nested value1
    const nb = [0];
    const item = exampleValueRead(u8, off, nb);
    if (item === null) return null;
    result.value1 = item;
    off += nb[0];
  }
  { // nested value2
    const nb = [0];
    const item = exampleValueRead(u8, off, nb);
    if (item === null) return null;
    result.value2 = item;
    off += nb[0];
  }
  if (outBytesRead) outBytesRead[0] = off - offset;
  return result;
}

export function exampleValuesEntryWrite(obj, u8, offset = 0) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  let off = offset;
  { // nested value1
    if (obj.value1 == null) return -1;
    const w = exampleValueWrite(obj.value1, u8, off);
    if (w < 0) return -1;
    off += w;
  }
  { // nested value2
    if (obj.value2 == null) return -1;
    const w = exampleValueWrite(obj.value2, u8, off);
    if (w < 0) return -1;
    off += w;
  }
  return off - offset;
}

export function exampleValuesEntrySize(obj) {
  let size = 0;
  size += exampleValueSize(obj.value1);
  size += exampleValueSize(obj.value2);
  return size;
}

export function exampleDataMessageRead(u8, offset = 0, outBytesRead = null) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  const result = {};
  let off = offset;
  { // nested top
    const nb = [0];
    const item = exampleValuesEntryRead(u8, off, nb);
    if (item === null) return null;
    result.top = item;
    off += nb[0];
  }
  { // nested bottom
    const nb = [0];
    const item = exampleValuesEntryRead(u8, off, nb);
    if (item === null) return null;
    result.bottom = item;
    off += nb[0];
  }
  if (outBytesRead) outBytesRead[0] = off - offset;
  return result;
}

export function exampleDataMessageWrite(obj, u8, offset = 0) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  let off = offset;
  { // nested top
    if (obj.top == null) return -1;
    const w = exampleValuesEntryWrite(obj.top, u8, off);
    if (w < 0) return -1;
    off += w;
  }
  { // nested bottom
    if (obj.bottom == null) return -1;
    const w = exampleValuesEntryWrite(obj.bottom, u8, off);
    if (w < 0) return -1;
    off += w;
  }
  return off - offset;
}

export function exampleDataMessageSize(obj) {
  let size = 0;
  size += exampleValuesEntrySize(obj.top);
  size += exampleValuesEntrySize(obj.bottom);
  return size;
}

export function exampleScreenValueEntryRead(u8, offset = 0, outBytesRead = null) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  const result = {};
  let off = offset;
  { // string suffix
    if (off + 1 > u8.byteLength) return null;
    const len = u8[off];
    off += 1;
    if (len > 12 || off + len > u8.byteLength) return null;
    result.suffix = decodeUtf8(u8, off, len);
    off += len;
  }
  { // nested color
    const nb = [0];
    const item = exampleColorRead(u8, off, nb);
    if (item === null) return null;
    result.color = item;
    off += nb[0];
  }
  if (outBytesRead) outBytesRead[0] = off - offset;
  return result;
}

export function exampleScreenValueEntryWrite(obj, u8, offset = 0) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  let off = offset;
  { // string suffix
    const enc = encodeUtf8Bounded(obj.suffix, 12);
    if (off + 1 + enc.length > u8.byteLength) return -1;
    u8[off] = enc.length & 0xFF;
    off += 1;
    u8.set(enc, off);
    off += enc.length;
  }
  { // nested color
    if (obj.color == null) return -1;
    const w = exampleColorWrite(obj.color, u8, off);
    if (w < 0) return -1;
    off += w;
  }
  return off - offset;
}

export function exampleScreenValueEntrySize(obj) {
  let size = 0;
  size += 1 + utf8Bounded(obj.suffix, 12);
  size += exampleColorSize(obj.color);
  return size;
}

export function exampleScreenEntryRead(u8, offset = 0, outBytesRead = null) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  const result = {};
  let off = offset;
  { // string label
    if (off + 1 > u8.byteLength) return null;
    const len = u8[off];
    off += 1;
    if (len > 32 || off + len > u8.byteLength) return null;
    result.label = decodeUtf8(u8, off, len);
    off += len;
  }
  { // nested color
    const nb = [0];
    const item = exampleColorRead(u8, off, nb);
    if (item === null) return null;
    result.color = item;
    off += nb[0];
  }
  { // nested value1
    const nb = [0];
    const item = exampleScreenValueEntryRead(u8, off, nb);
    if (item === null) return null;
    result.value1 = item;
    off += nb[0];
  }
  { // nested value2
    const nb = [0];
    const item = exampleScreenValueEntryRead(u8, off, nb);
    if (item === null) return null;
    result.value2 = item;
    off += nb[0];
  }
  if (outBytesRead) outBytesRead[0] = off - offset;
  return result;
}

export function exampleScreenEntryWrite(obj, u8, offset = 0) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  let off = offset;
  { // string label
    const enc = encodeUtf8Bounded(obj.label, 32);
    if (off + 1 + enc.length > u8.byteLength) return -1;
    u8[off] = enc.length & 0xFF;
    off += 1;
    u8.set(enc, off);
    off += enc.length;
  }
  { // nested color
    if (obj.color == null) return -1;
    const w = exampleColorWrite(obj.color, u8, off);
    if (w < 0) return -1;
    off += w;
  }
  { // nested value1
    if (obj.value1 == null) return -1;
    const w = exampleScreenValueEntryWrite(obj.value1, u8, off);
    if (w < 0) return -1;
    off += w;
  }
  { // nested value2
    if (obj.value2 == null) return -1;
    const w = exampleScreenValueEntryWrite(obj.value2, u8, off);
    if (w < 0) return -1;
    off += w;
  }
  return off - offset;
}

export function exampleScreenEntrySize(obj) {
  let size = 0;
  size += 1 + utf8Bounded(obj.label, 32);
  size += exampleColorSize(obj.color);
  size += exampleScreenValueEntrySize(obj.value1);
  size += exampleScreenValueEntrySize(obj.value2);
  return size;
}

export function exampleScreenMessageRead(u8, offset = 0, outBytesRead = null) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  const result = {};
  let off = offset;
  if (off + 1 > u8.byteLength) return null;
  result.index = (u8[off] << 24 >> 24);
  off += 1;
  if (off + 1 > u8.byteLength) return null;
  result.flags = u8[off];
  off += 1;
  { // nested top
    const nb = [0];
    const item = exampleScreenEntryRead(u8, off, nb);
    if (item === null) return null;
    result.top = item;
    off += nb[0];
  }
  { // nested bottom
    const nb = [0];
    const item = exampleScreenEntryRead(u8, off, nb);
    if (item === null) return null;
    result.bottom = item;
    off += nb[0];
  }
  if (outBytesRead) outBytesRead[0] = off - offset;
  return result;
}

export function exampleScreenMessageWrite(obj, u8, offset = 0) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  let off = offset;
  if (off + 1 > u8.byteLength) return -1;
  u8[off] = obj.index & 0xFF;
  off += 1;
  if (off + 1 > u8.byteLength) return -1;
  u8[off] = obj.flags & 0xFF;
  off += 1;
  { // nested top
    if (obj.top == null) return -1;
    const w = exampleScreenEntryWrite(obj.top, u8, off);
    if (w < 0) return -1;
    off += w;
  }
  { // nested bottom
    if (obj.bottom == null) return -1;
    const w = exampleScreenEntryWrite(obj.bottom, u8, off);
    if (w < 0) return -1;
    off += w;
  }
  return off - offset;
}

export function exampleScreenMessageSize(obj) {
  let size = 0;
  size += 1;
  size += 1;
  size += exampleScreenEntrySize(obj.top);
  size += exampleScreenEntrySize(obj.bottom);
  return size;
}

export function exampleNopMessageRead(u8, offset = 0, outBytesRead = null) {
  const result = {};
  if (outBytesRead) outBytesRead[0] = 0;
  return result;
}

export function exampleNopMessageWrite(obj, u8, offset = 0) {
  return 0;
}

export function exampleNopMessageSize(obj) {
  return 0;
}

export function exampleClearMessageRead(u8, offset = 0, outBytesRead = null) {
  const result = {};
  if (outBytesRead) outBytesRead[0] = 0;
  return result;
}

export function exampleClearMessageWrite(obj, u8, offset = 0) {
  return 0;
}

export function exampleClearMessageSize(obj) {
  return 0;
}

export function exampleModeMessageRead(u8, offset = 0, outBytesRead = null) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  const result = {};
  let off = offset;
  if (off + 1 > u8.byteLength) return null;
  result.mode = u8[off];
  off += 1;
  if (outBytesRead) outBytesRead[0] = off - offset;
  return result;
}

export function exampleModeMessageWrite(obj, u8, offset = 0) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  let off = offset;
  if (off + 1 > u8.byteLength) return -1;
  u8[off] = obj.mode & 0xFF;
  off += 1;
  return off - offset;
}

export function exampleModeMessageSize(obj) {
  let size = 0;
  size += 1;
  return size;
}

export function exampleResetScreenMessageRead(u8, offset = 0, outBytesRead = null) {
  const result = {};
  if (outBytesRead) outBytesRead[0] = 0;
  return result;
}

export function exampleResetScreenMessageWrite(obj, u8, offset = 0) {
  return 0;
}

export function exampleResetScreenMessageSize(obj) {
  return 0;
}

export function exampleIdentRequestMessageRead(u8, offset = 0, outBytesRead = null) {
  const result = {};
  if (outBytesRead) outBytesRead[0] = 0;
  return result;
}

export function exampleIdentRequestMessageWrite(obj, u8, offset = 0) {
  return 0;
}

export function exampleIdentRequestMessageSize(obj) {
  return 0;
}

export function exampleIdentMessageRead(u8, offset = 0, outBytesRead = null) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  const result = {};
  let off = offset;
  if (off + 2 > u8.byteLength) return null;
  result.versionMajor = dv.getUint16(off, true);
  off += 2;
  if (off + 2 > u8.byteLength) return null;
  result.versionMinor = dv.getUint16(off, true);
  off += 2;
  if (off + 8 > u8.byteLength) return null;
  result.build = dv.getBigUint64(off, true);
  off += 8;
  if (off + 2 > u8.byteLength) return null;
  result.id = dv.getUint16(off, true);
  off += 2;
  { // array macAddress
    const a = new Array(6);
    for (let i = 0; i < 6; i++) {
      if (off + 1 > u8.byteLength) return null;
      a[i] = u8[off];
      off += 1;
    }
    result.macAddress = a;
  }
  { // string displayName
    if (off + 1 > u8.byteLength) return null;
    const len = u8[off];
    off += 1;
    if (len > 64 || off + len > u8.byteLength) return null;
    result.displayName = decodeUtf8(u8, off, len);
    off += len;
  }
  { // string slug
    if (off + 1 > u8.byteLength) return null;
    const len = u8[off];
    off += 1;
    if (len > 64 || off + len > u8.byteLength) return null;
    result.slug = decodeUtf8(u8, off, len);
    off += len;
  }
  if (off + 2 > u8.byteLength) return null;
  result.horizontalResolution = dv.getUint16(off, true);
  off += 2;
  if (off + 2 > u8.byteLength) return null;
  result.verticalResolution = dv.getUint16(off, true);
  off += 2;
  if (off + 1 > u8.byteLength) return null;
  result.isMonochrome = (u8[off]) !== 0;
  off += 1;
  if (off + 4 > u8.byteLength) return null;
  result.dpi = dv.getFloat32(off, true);
  off += 4;
  if (off + 4 > u8.byteLength) return null;
  result.pixelSize = dv.getFloat32(off, true);
  off += 4;
  if (off + 1 > u8.byteLength) return null;
  result.inputType = u8[off];
  off += 1;
  if (outBytesRead) outBytesRead[0] = off - offset;
  return result;
}

export function exampleIdentMessageWrite(obj, u8, offset = 0) {
  const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
  let off = offset;
  if (off + 2 > u8.byteLength) return -1;
  dv.setUint16(off, obj.versionMajor, true);
  off += 2;
  if (off + 2 > u8.byteLength) return -1;
  dv.setUint16(off, obj.versionMinor, true);
  off += 2;
  if (off + 8 > u8.byteLength) return -1;
  dv.setBigUint64(off, BigInt(obj.build), true);
  off += 8;
  if (off + 2 > u8.byteLength) return -1;
  dv.setUint16(off, obj.id, true);
  off += 2;
  { // array macAddress
    const a = obj.macAddress;
    const n = (a == null) ? 0 : Math.min(a.length, 6);
    for (let i = 0; i < n; i++) {
      if (off + 1 > u8.byteLength) return -1;
      u8[off] = a[i] & 0xFF;
      off += 1;
    }
    for (let i = n; i < 6; i++) {
      if (off + 1 > u8.byteLength) return -1;
      u8[off] = 0 & 0xFF;
      off += 1;
    }
  }
  { // string displayName
    const enc = encodeUtf8Bounded(obj.displayName, 64);
    if (off + 1 + enc.length > u8.byteLength) return -1;
    u8[off] = enc.length & 0xFF;
    off += 1;
    u8.set(enc, off);
    off += enc.length;
  }
  { // string slug
    const enc = encodeUtf8Bounded(obj.slug, 64);
    if (off + 1 + enc.length > u8.byteLength) return -1;
    u8[off] = enc.length & 0xFF;
    off += 1;
    u8.set(enc, off);
    off += enc.length;
  }
  if (off + 2 > u8.byteLength) return -1;
  dv.setUint16(off, obj.horizontalResolution, true);
  off += 2;
  if (off + 2 > u8.byteLength) return -1;
  dv.setUint16(off, obj.verticalResolution, true);
  off += 2;
  if (off + 1 > u8.byteLength) return -1;
  u8[off] = (obj.isMonochrome ? 1 : 0) & 0xFF;
  off += 1;
  if (off + 4 > u8.byteLength) return -1;
  dv.setFloat32(off, obj.dpi, true);
  off += 4;
  if (off + 4 > u8.byteLength) return -1;
  dv.setFloat32(off, obj.pixelSize, true);
  off += 4;
  if (off + 1 > u8.byteLength) return -1;
  u8[off] = obj.inputType & 0xFF;
  off += 1;
  return off - offset;
}

export function exampleIdentMessageSize(obj) {
  let size = 0;
  size += 2;
  size += 2;
  size += 8;
  size += 2;
  size += 6 * 1;
  size += 1 + utf8Bounded(obj.displayName, 64);
  size += 1 + utf8Bounded(obj.slug, 64);
  size += 2;
  size += 2;
  size += 1;
  size += 4;
  size += 4;
  size += 1;
  return size;
}
