// Auto-generated by buffers_gen_cs.py — do not edit manually.
// Shared support types for wire buffer reading/writing.
#nullable disable
using System;
using System.Text;

namespace Htcw;

/// <summary>Status codes mirroring the C buffers.h enum.</summary>
internal static class BuffersStatus
{
    public const int Success  =  0;
    public const int Eof      = -1;
    public const int ErrorEof = -2;
}

/// <summary>Wire string encode/decode helpers used by generated code.</summary>
internal static class Buffers
{
    /// <summary>
    /// Decode a fixed-length UTF-8 byte field into a string.
    /// Strips everything at and after the first null byte.
    /// </summary>
    internal static string DecodeUtf8(ReadOnlySpan<byte> span)
    {
        int len = span.IndexOf((byte)0);
        if (len < 0) len = span.Length;
        return Encoding.UTF8.GetString(span.Slice(0, len));
    }

    /// <summary>
    /// Decode a fixed-length UTF-16LE byte field into a string.
    /// Strips everything at and after the first null char (0x0000).
    /// </summary>
    internal static string DecodeUtf16Le(ReadOnlySpan<byte> span)
    {
        // Find first null char (two zero bytes aligned on even boundary)
        int len = span.Length & ~1; // round down to even
        for (int i = 0; i < len; i += 2)
        {
            if (span[i] == 0 && span[i + 1] == 0) { len = i; break; }
        }
        return Encoding.Unicode.GetString(span.Slice(0, len));
    }

    /// <summary>
    /// Encode a string as UTF-8 into a fixed-length span, zero-padded.
    /// Truncates on a valid UTF-8 code-point boundary so no broken sequences
    /// are written. The destination is always fully written (zero-padded).
    /// </summary>
    internal static void EncodeUtf8(string value, Span<byte> dest)
    {
        dest.Clear();
        if (string.IsNullOrEmpty(value)) return;
        // Encode into a temporary buffer then find the safe truncation point
        byte[] encoded = Encoding.UTF8.GetBytes(value);
        int copyLen = Math.Min(encoded.Length, dest.Length);
        // Walk back from copyLen to find a valid UTF-8 boundary
        // A continuation byte has the form 10xxxxxx (0x80-0xBF).
        // A leading byte of a multi-byte sequence starts with 11xxxxxx.
        while (copyLen > 0 && (encoded[copyLen - 1] & 0xC0) == 0x80)
            copyLen--; // back up past continuation bytes
        // If we're now pointing at a leading byte, check it's complete
        if (copyLen > 0)
        {
            byte lead = encoded[copyLen - 1];
            int seqLen = lead < 0x80 ? 1
                       : lead >= 0xF0 ? 4
                       : lead >= 0xE0 ? 3
                       : 2;
            // Count how many bytes of that sequence we actually have
            int have = 1;
            int scan = copyLen - 2;
            while (scan >= 0 && (encoded[scan] & 0xC0) == 0x80 && have < seqLen)
            { have++; scan--; }
            if (have < seqLen) copyLen--; // incomplete sequence: drop it
        }
        encoded.AsSpan(0, copyLen).CopyTo(dest);
    }

    /// <summary>
    /// Encode a string as UTF-16LE into a fixed-length span, zero-padded.
    /// Truncates on a valid UTF-16 code-unit boundary (never splits a
    /// surrogate pair). The destination is always fully written.
    /// </summary>
    internal static void EncodeUtf16Le(string value, Span<byte> dest)
    {
        dest.Clear();
        if (string.IsNullOrEmpty(value)) return;
        byte[] encoded = Encoding.Unicode.GetBytes(value); // UTF-16LE
        int maxChars = dest.Length / 2;
        int copyChars = Math.Min(encoded.Length / 2, maxChars);
        // If the last char is a high surrogate, drop it
        if (copyChars > 0)
        {
            char last = (char)(encoded[(copyChars - 1) * 2] | (encoded[(copyChars - 1) * 2 + 1] << 8));
            if (char.IsHighSurrogate(last)) copyChars--;
        }
        encoded.AsSpan(0, copyChars * 2).CopyTo(dest);
    }
}
#nullable restore
