// Auto-generated by buffers_gen_cs.py - do not edit manually.
// Shared support types for wire buffer reading/writing.
#nullable disable
using System;
using System.Text;

namespace Htcw;

/// <summary>Status codes mirroring the C buffers.h enum.</summary>
internal static class BuffersStatus
{
    public const int Success  =  0;
    public const int Eof      = -1;
    public const int ErrorEof = -2;
}

/// <summary>Wire string encode/decode helpers used by generated code.</summary>
internal static class Buffers
{
    /// <summary>
    /// Decode a fixed-length UTF-8 byte field into a string.
    /// Strips everything at and after the first null byte.
    /// </summary>
    internal static string DecodeUtf8(ReadOnlySpan<byte> span)
    {
        int len = span.IndexOf((byte)0);
        if (len < 0) len = span.Length;
        return Encoding.UTF8.GetString(span.Slice(0, len));
    }

    /// <summary>
    /// Decode a fixed-length UTF-16LE byte field into a string.
    /// Strips everything at and after the first null char (0x0000).
    /// </summary>
    internal static string DecodeUtf16LE(ReadOnlySpan<byte> span)
    {
        // Find first null char (two zero bytes aligned on even boundary)
        int len = span.Length & ~1; // round down to even
        for (int i = 0; i < len; i += 2)
        {
            if (span[i] == 0 && span[i + 1] == 0) { len = i; break; }
        }
        return Encoding.Unicode.GetString(span.Slice(0, len));
    }

    /// <summary>
    /// Encode a string as UTF-8 into a fixed-length span, zero-padded.
    /// Uses Encoder.Convert to guarantee truncation on a valid code-point
    /// boundary - no partial sequences are ever written.
    /// </summary>
    internal static void EncodeUtf8(string value, Span<byte> dest)
    {
        dest.Clear();
        if (string.IsNullOrEmpty(value)) return;
        var encoder = Encoding.UTF8.GetEncoder();
        var chars = value.AsSpan();
        encoder.Convert(chars, dest, flush: true,
            out int charsUsed, out int bytesUsed, out bool completed);
    }

    /// <summary>
    /// Encode a string as UTF-16LE into a fixed-length span, zero-padded.
    /// Uses Encoder.Convert to guarantee truncation on a valid code-unit
    /// boundary - surrogate pairs are never split.
    /// </summary>
    internal static void EncodeUtf16LE(string value, Span<byte> dest)
    {
        dest.Clear();
        if (string.IsNullOrEmpty(value)) return;
        var encoder = Encoding.Unicode.GetEncoder();
        var chars = value.AsSpan();
        encoder.Convert(chars, dest, flush: true,
            out int charsUsed, out int bytesUsed, out bool completed);
    }
}
#nullable restore
