// <auto-generated />
// Auto-generated by buffers_gen_cs.py - do not edit manually.
#nullable disable
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Htcw;

namespace SerialFrameDemo;

enum STMessageCommand : byte
{
    CmdNone = 0,
    CmdEspIdfVersion = 1,
    CmdRng = 2,
    CmdGpioMode = 3,
    CmdGpioGet = 4,
    CmdGpioSet = 5,
    CmdMacAddress = 6,
    CmdEspIdfVersionResponse = 7,
    CmdRngResponse = 8,
    CmdGpioGetResponse = 9,
    CmdMacAddressResponse = 10,
}

enum STGpioMode : byte
{
    ModeInput = 0,
    ModeInputPullup = 1,
    ModeInputPulldown = 2,
    ModeOutput = 3,
    ModeOutputOpenDrain = 4,
}

struct InterfaceMaxSize
{
    internal const int Value = 68;
}

partial class STEspIdfVersionMessage
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryRead(ReadOnlySpan<byte> span, out STEspIdfVersionMessage result, out int bytesRead)
    {
        result = new STEspIdfVersionMessage();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(Stream stream, out STEspIdfVersionMessage result, out int bytesRead)
    {
        result = new STEspIdfVersionMessage();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

partial class STRngMessage
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryRead(ReadOnlySpan<byte> span, out STRngMessage result, out int bytesRead)
    {
        result = new STRngMessage();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(Stream stream, out STRngMessage result, out int bytesRead)
    {
        result = new STRngMessage();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

partial class STGpioGetMessage
{
    internal const int StructMaxSize = 8;

    internal ulong Mask { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 8;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STGpioGetMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STGpioGetMessage();
        int offset = 0;
        if (span.Length - offset < 8) return false;
        result.Mask = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(offset));
        offset += 8;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(offset), Mask);
        offset += 8;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STGpioGetMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STGpioGetMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[8];
        int n = stream.Read(buf);
        if (n < 8) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[8];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STGpioSetMessage
{
    internal const int StructMaxSize = 16;

    internal ulong Mask { get; set; }
    internal ulong Values { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 8;
            size += 8;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STGpioSetMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STGpioSetMessage();
        int offset = 0;
        if (span.Length - offset < 8) return false;
        result.Mask = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(offset));
        offset += 8;
        if (span.Length - offset < 8) return false;
        result.Values = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(offset));
        offset += 8;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(offset), Mask);
        offset += 8;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(offset), Values);
        offset += 8;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STGpioSetMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STGpioSetMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[16];
        int n = stream.Read(buf);
        if (n < 16) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[16];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STGpioModeMessage
{
    internal const int StructMaxSize = 2;

    internal byte Gpio { get; set; }
    internal STGpioMode Mode { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1;
            size += 1;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STGpioModeMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STGpioModeMessage();
        int offset = 0;
        if (span.Length - offset < 1) return false;
        result.Gpio = span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.Mode = (STGpioMode)span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 1) return false;
        span[offset] = Gpio;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = (byte)Mode;
        offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STGpioModeMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STGpioModeMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[2];
        int n = stream.Read(buf);
        if (n < 2) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[2];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STMacAddressMessage
{
    internal const int StructMaxSize = 0;

    internal int SizeOfStruct => 0;

    internal static bool TryRead(ReadOnlySpan<byte> span, out STMacAddressMessage result, out int bytesRead)
    {
        result = new STMacAddressMessage();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

    internal static bool TryRead(Stream stream, out STMacAddressMessage result, out int bytesRead)
    {
        result = new STMacAddressMessage();
        bytesRead = 0;
        return true;
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        bytesWritten = 0;
        return true;
    }

}

partial class STEspIdfVersionResponseMessage
{
    internal const int StructMaxSize = 68;

    internal string Version { get; set; }
    internal byte Major { get; set; }
    internal byte Minor { get; set; }
    internal byte Patch { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 1 + (string.IsNullOrEmpty(Version) ? 0 : Math.Min(Encoding.UTF8.GetByteCount(Version), 64));
            size += 1;
            size += 1;
            size += 1;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STEspIdfVersionResponseMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STEspIdfVersionResponseMessage();
        int offset = 0;
        if (span.Length - offset < 1) return false;
        {
            int _len_Version = (int)(span[offset]);
            offset += 1;
            if (_len_Version > 64 || span.Length - offset < _len_Version) return false;
            result.Version = Encoding.UTF8.GetString(span.Slice(offset, _len_Version));
            offset += _len_Version;
        }
        if (span.Length - offset < 1) return false;
        result.Major = span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.Minor = span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.Patch = span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        {
            int _byteLen_Version = string.IsNullOrEmpty(Version) ? 0 : Encoding.UTF8.GetByteCount(Version);
            if (_byteLen_Version > 64) _byteLen_Version = 64;
            if (span.Length - offset < 1 + _byteLen_Version) return false;
            span[offset] = (byte)_byteLen_Version;
            offset += 1;
            if (_byteLen_Version > 0)
            {
                Encoding.UTF8.GetBytes(Version.AsSpan(), span.Slice(offset, _byteLen_Version));
                offset += _byteLen_Version;
            }
        }
        if (span.Length - offset < 1) return false;
        span[offset] = Major;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = Minor;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = Patch;
        offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STEspIdfVersionResponseMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STEspIdfVersionResponseMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[68];
        int n = stream.Read(buf);
        if (n < 68) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[68];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STRngResponseMessage
{
    internal const int StructMaxSize = 4;

    internal uint Value { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 4;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STRngResponseMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STRngResponseMessage();
        int offset = 0;
        if (span.Length - offset < 4) return false;
        result.Value = BinaryPrimitives.ReadUInt32LittleEndian(span.Slice(offset));
        offset += 4;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 4) return false;
        BinaryPrimitives.WriteUInt32LittleEndian(span.Slice(offset), Value);
        offset += 4;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STRngResponseMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STRngResponseMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[4];
        int n = stream.Read(buf);
        if (n < 4) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[4];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STGpioGetResponseMessage
{
    internal const int StructMaxSize = 8;

    internal ulong Values { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 8;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STGpioGetResponseMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STGpioGetResponseMessage();
        int offset = 0;
        if (span.Length - offset < 8) return false;
        result.Values = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(offset));
        offset += 8;
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(offset), Values);
        offset += 8;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STGpioGetResponseMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STGpioGetResponseMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[8];
        int n = stream.Read(buf);
        if (n < 8) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[8];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STMacAddressResponseMessage
{
    internal const int StructMaxSize = 6;

    internal byte[] Address { get; set; }

    internal int SizeOfStruct
    {
        get
        {
            int size = 0;
            size += 6 * 1;
            return size;
        }
    }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STMacAddressResponseMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STMacAddressResponseMessage();
        int offset = 0;
        {
            var _arr_Address = new byte[6];
            for (int i = 0; i < 6; i++)
            {
                if (span.Length - offset < 1) return false;
                _arr_Address[i] = span[offset];
                offset += 1;
            }
            result.Address = _arr_Address;
        }
        bytesRead = offset;
        return true;
    }

    private bool TryWriteCore(Span<byte> span, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        {
            int _count_Address = Address != null ? Math.Min(Address.Length, 6) : 0;
            for (int i = 0; i < _count_Address; i++)
            {
                if (span.Length - offset < 1) return false;
                span[offset] = Address[i];
                offset += 1;
            }
            for (int i = _count_Address; i < 6; i++)
            {
                if (span.Length - offset < 1) return false;
                span[offset] = (byte)0;
                offset += 1;
            }
        }
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STMacAddressResponseMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal bool TryWrite(Span<byte> destination, out int bytesWritten)
    {
        return TryWriteCore(destination, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STMacAddressResponseMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[6];
        int n = stream.Read(buf);
        if (n < 6) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal bool TryWrite(Stream stream, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[6];
        if (!TryWriteCore(buf, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

#nullable restore