// Auto-generated by buffers_gen_cs.py — do not edit manually.
#nullable disable
using System;
using System.Buffers.Binary;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Htcw;

namespace SerialFrameDemo;

enum STMessageCommand : byte
{
    CmdNone = 0,
    CmdReqEspIdf = 1,
    CmdReqGetGpio = 2,
    CmdReqSetGpio = 3,
    CmdReqRng = 4,
    CmdReqMac = 5,
    CmdEspIdf = 6,
    CmdGpio = 7,
    CmdRng = 8,
    CmdMac = 9,
    CmdNop = 10,
}

struct InterfaceMaxSize
{
    internal const int Value = 67;
}

partial class STReqEspIdfMessage
{
    internal const int SizeOfStruct = 0;


    private static bool TryReadCore(ReadOnlySpan<byte> span, out STReqEspIdfMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STReqEspIdfMessage();
        int offset = 0;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteCore(Span<byte> span, STReqEspIdfMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        bytesWritten = offset;
        return true;
    }

    private static bool TryReadBECore(ReadOnlySpan<byte> span, out STReqEspIdfMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STReqEspIdfMessage();
        int offset = 0;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteBECore(Span<byte> span, STReqEspIdfMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STReqEspIdfMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal static bool TryWrite(Span<byte> destination, STReqEspIdfMessage value, out int bytesWritten)
    {
        return TryWriteCore(destination, value, out bytesWritten);
    }

    internal static bool TryReadBE(ReadOnlySpan<byte> span, out STReqEspIdfMessage result, out int bytesRead)
    {
        return TryReadBECore(span, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Span<byte> destination, STReqEspIdfMessage value, out int bytesWritten)
    {
        return TryWriteBECore(destination, value, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STReqEspIdfMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[0];
        int n = stream.Read(buf);
        if (n < 0) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal static bool TryWrite(Stream stream, STReqEspIdfMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[0];
        if (!TryWriteCore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

    internal static bool TryReadBE(Stream stream, out STReqEspIdfMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[0];
        int n = stream.Read(buf);
        if (n < 0) { result = null; bytesRead = n; return false; }
        return TryReadBECore(buf, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Stream stream, STReqEspIdfMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[0];
        if (!TryWriteBECore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STReqGetGpioMessage
{
    internal const int SizeOfStruct = 8;

    internal ulong Mask { get; set; }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STReqGetGpioMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STReqGetGpioMessage();
        int offset = 0;
        if (span.Length - offset < 8) return false;
        result.Mask = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(offset));
        offset += 8;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteCore(Span<byte> span, STReqGetGpioMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(offset), value.Mask);
        offset += 8;
        bytesWritten = offset;
        return true;
    }

    private static bool TryReadBECore(ReadOnlySpan<byte> span, out STReqGetGpioMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STReqGetGpioMessage();
        int offset = 0;
        if (span.Length - offset < 8) return false;
        result.Mask = BinaryPrimitives.ReadUInt64BigEndian(span.Slice(offset));
        offset += 8;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteBECore(Span<byte> span, STReqGetGpioMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64BigEndian(span.Slice(offset), value.Mask);
        offset += 8;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STReqGetGpioMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal static bool TryWrite(Span<byte> destination, STReqGetGpioMessage value, out int bytesWritten)
    {
        return TryWriteCore(destination, value, out bytesWritten);
    }

    internal static bool TryReadBE(ReadOnlySpan<byte> span, out STReqGetGpioMessage result, out int bytesRead)
    {
        return TryReadBECore(span, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Span<byte> destination, STReqGetGpioMessage value, out int bytesWritten)
    {
        return TryWriteBECore(destination, value, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STReqGetGpioMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[8];
        int n = stream.Read(buf);
        if (n < 8) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal static bool TryWrite(Stream stream, STReqGetGpioMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[8];
        if (!TryWriteCore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

    internal static bool TryReadBE(Stream stream, out STReqGetGpioMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[8];
        int n = stream.Read(buf);
        if (n < 8) { result = null; bytesRead = n; return false; }
        return TryReadBECore(buf, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Stream stream, STReqGetGpioMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[8];
        if (!TryWriteBECore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STReqSetGpioMessage
{
    internal const int SizeOfStruct = 16;

    internal ulong Mask { get; set; }
    internal ulong Levels { get; set; }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STReqSetGpioMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STReqSetGpioMessage();
        int offset = 0;
        if (span.Length - offset < 8) return false;
        result.Mask = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(offset));
        offset += 8;
        if (span.Length - offset < 8) return false;
        result.Levels = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(offset));
        offset += 8;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteCore(Span<byte> span, STReqSetGpioMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(offset), value.Mask);
        offset += 8;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(offset), value.Levels);
        offset += 8;
        bytesWritten = offset;
        return true;
    }

    private static bool TryReadBECore(ReadOnlySpan<byte> span, out STReqSetGpioMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STReqSetGpioMessage();
        int offset = 0;
        if (span.Length - offset < 8) return false;
        result.Mask = BinaryPrimitives.ReadUInt64BigEndian(span.Slice(offset));
        offset += 8;
        if (span.Length - offset < 8) return false;
        result.Levels = BinaryPrimitives.ReadUInt64BigEndian(span.Slice(offset));
        offset += 8;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteBECore(Span<byte> span, STReqSetGpioMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64BigEndian(span.Slice(offset), value.Mask);
        offset += 8;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64BigEndian(span.Slice(offset), value.Levels);
        offset += 8;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STReqSetGpioMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal static bool TryWrite(Span<byte> destination, STReqSetGpioMessage value, out int bytesWritten)
    {
        return TryWriteCore(destination, value, out bytesWritten);
    }

    internal static bool TryReadBE(ReadOnlySpan<byte> span, out STReqSetGpioMessage result, out int bytesRead)
    {
        return TryReadBECore(span, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Span<byte> destination, STReqSetGpioMessage value, out int bytesWritten)
    {
        return TryWriteBECore(destination, value, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STReqSetGpioMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[16];
        int n = stream.Read(buf);
        if (n < 16) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal static bool TryWrite(Stream stream, STReqSetGpioMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[16];
        if (!TryWriteCore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

    internal static bool TryReadBE(Stream stream, out STReqSetGpioMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[16];
        int n = stream.Read(buf);
        if (n < 16) { result = null; bytesRead = n; return false; }
        return TryReadBECore(buf, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Stream stream, STReqSetGpioMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[16];
        if (!TryWriteBECore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STReqRngMessage
{
    internal const int SizeOfStruct = 0;


    private static bool TryReadCore(ReadOnlySpan<byte> span, out STReqRngMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STReqRngMessage();
        int offset = 0;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteCore(Span<byte> span, STReqRngMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        bytesWritten = offset;
        return true;
    }

    private static bool TryReadBECore(ReadOnlySpan<byte> span, out STReqRngMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STReqRngMessage();
        int offset = 0;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteBECore(Span<byte> span, STReqRngMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STReqRngMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal static bool TryWrite(Span<byte> destination, STReqRngMessage value, out int bytesWritten)
    {
        return TryWriteCore(destination, value, out bytesWritten);
    }

    internal static bool TryReadBE(ReadOnlySpan<byte> span, out STReqRngMessage result, out int bytesRead)
    {
        return TryReadBECore(span, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Span<byte> destination, STReqRngMessage value, out int bytesWritten)
    {
        return TryWriteBECore(destination, value, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STReqRngMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[0];
        int n = stream.Read(buf);
        if (n < 0) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal static bool TryWrite(Stream stream, STReqRngMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[0];
        if (!TryWriteCore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

    internal static bool TryReadBE(Stream stream, out STReqRngMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[0];
        int n = stream.Read(buf);
        if (n < 0) { result = null; bytesRead = n; return false; }
        return TryReadBECore(buf, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Stream stream, STReqRngMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[0];
        if (!TryWriteBECore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STReqMacMessage
{
    internal const int SizeOfStruct = 0;


    private static bool TryReadCore(ReadOnlySpan<byte> span, out STReqMacMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STReqMacMessage();
        int offset = 0;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteCore(Span<byte> span, STReqMacMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        bytesWritten = offset;
        return true;
    }

    private static bool TryReadBECore(ReadOnlySpan<byte> span, out STReqMacMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STReqMacMessage();
        int offset = 0;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteBECore(Span<byte> span, STReqMacMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STReqMacMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal static bool TryWrite(Span<byte> destination, STReqMacMessage value, out int bytesWritten)
    {
        return TryWriteCore(destination, value, out bytesWritten);
    }

    internal static bool TryReadBE(ReadOnlySpan<byte> span, out STReqMacMessage result, out int bytesRead)
    {
        return TryReadBECore(span, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Span<byte> destination, STReqMacMessage value, out int bytesWritten)
    {
        return TryWriteBECore(destination, value, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STReqMacMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[0];
        int n = stream.Read(buf);
        if (n < 0) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal static bool TryWrite(Stream stream, STReqMacMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[0];
        if (!TryWriteCore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

    internal static bool TryReadBE(Stream stream, out STReqMacMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[0];
        int n = stream.Read(buf);
        if (n < 0) { result = null; bytesRead = n; return false; }
        return TryReadBECore(buf, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Stream stream, STReqMacMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[0];
        if (!TryWriteBECore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STEspIdfMessage
{
    internal const int SizeOfStruct = 67;

    internal string Version { get; set; }
    internal byte Major { get; set; }
    internal byte Minor { get; set; }
    internal byte Patch { get; set; }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STEspIdfMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STEspIdfMessage();
        int offset = 0;
        if (span.Length - offset < 64) return false;
        result.Version = Buffers.DecodeUtf8(span.Slice(offset, 64));
        offset += 64;
        if (span.Length - offset < 1) return false;
        result.Major = span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.Minor = span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.Patch = span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteCore(Span<byte> span, STEspIdfMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 64) return false;
        Buffers.EncodeUtf8(value.Version, span.Slice(offset, 64));
        offset += 64;
        if (span.Length - offset < 1) return false;
        span[offset] = value.Major;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = value.Minor;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = value.Patch;
        offset += 1;
        bytesWritten = offset;
        return true;
    }

    private static bool TryReadBECore(ReadOnlySpan<byte> span, out STEspIdfMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STEspIdfMessage();
        int offset = 0;
        if (span.Length - offset < 64) return false;
        result.Version = Buffers.DecodeUtf8(span.Slice(offset, 64));
        offset += 64;
        if (span.Length - offset < 1) return false;
        result.Major = span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.Minor = span[offset];
        offset += 1;
        if (span.Length - offset < 1) return false;
        result.Patch = span[offset];
        offset += 1;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteBECore(Span<byte> span, STEspIdfMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 64) return false;
        Buffers.EncodeUtf8(value.Version, span.Slice(offset, 64));
        offset += 64;
        if (span.Length - offset < 1) return false;
        span[offset] = value.Major;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = value.Minor;
        offset += 1;
        if (span.Length - offset < 1) return false;
        span[offset] = value.Patch;
        offset += 1;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STEspIdfMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal static bool TryWrite(Span<byte> destination, STEspIdfMessage value, out int bytesWritten)
    {
        return TryWriteCore(destination, value, out bytesWritten);
    }

    internal static bool TryReadBE(ReadOnlySpan<byte> span, out STEspIdfMessage result, out int bytesRead)
    {
        return TryReadBECore(span, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Span<byte> destination, STEspIdfMessage value, out int bytesWritten)
    {
        return TryWriteBECore(destination, value, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STEspIdfMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[67];
        int n = stream.Read(buf);
        if (n < 67) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal static bool TryWrite(Stream stream, STEspIdfMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[67];
        if (!TryWriteCore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

    internal static bool TryReadBE(Stream stream, out STEspIdfMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[67];
        int n = stream.Read(buf);
        if (n < 67) { result = null; bytesRead = n; return false; }
        return TryReadBECore(buf, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Stream stream, STEspIdfMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[67];
        if (!TryWriteBECore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STGpioMessage
{
    internal const int SizeOfStruct = 8;

    internal ulong Levels { get; set; }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STGpioMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STGpioMessage();
        int offset = 0;
        if (span.Length - offset < 8) return false;
        result.Levels = BinaryPrimitives.ReadUInt64LittleEndian(span.Slice(offset));
        offset += 8;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteCore(Span<byte> span, STGpioMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64LittleEndian(span.Slice(offset), value.Levels);
        offset += 8;
        bytesWritten = offset;
        return true;
    }

    private static bool TryReadBECore(ReadOnlySpan<byte> span, out STGpioMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STGpioMessage();
        int offset = 0;
        if (span.Length - offset < 8) return false;
        result.Levels = BinaryPrimitives.ReadUInt64BigEndian(span.Slice(offset));
        offset += 8;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteBECore(Span<byte> span, STGpioMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 8) return false;
        BinaryPrimitives.WriteUInt64BigEndian(span.Slice(offset), value.Levels);
        offset += 8;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STGpioMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal static bool TryWrite(Span<byte> destination, STGpioMessage value, out int bytesWritten)
    {
        return TryWriteCore(destination, value, out bytesWritten);
    }

    internal static bool TryReadBE(ReadOnlySpan<byte> span, out STGpioMessage result, out int bytesRead)
    {
        return TryReadBECore(span, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Span<byte> destination, STGpioMessage value, out int bytesWritten)
    {
        return TryWriteBECore(destination, value, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STGpioMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[8];
        int n = stream.Read(buf);
        if (n < 8) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal static bool TryWrite(Stream stream, STGpioMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[8];
        if (!TryWriteCore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

    internal static bool TryReadBE(Stream stream, out STGpioMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[8];
        int n = stream.Read(buf);
        if (n < 8) { result = null; bytesRead = n; return false; }
        return TryReadBECore(buf, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Stream stream, STGpioMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[8];
        if (!TryWriteBECore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STRngMessage
{
    internal const int SizeOfStruct = 4;

    internal uint Value { get; set; }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STRngMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STRngMessage();
        int offset = 0;
        if (span.Length - offset < 4) return false;
        result.Value = BinaryPrimitives.ReadUInt32LittleEndian(span.Slice(offset));
        offset += 4;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteCore(Span<byte> span, STRngMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 4) return false;
        BinaryPrimitives.WriteUInt32LittleEndian(span.Slice(offset), value.Value);
        offset += 4;
        bytesWritten = offset;
        return true;
    }

    private static bool TryReadBECore(ReadOnlySpan<byte> span, out STRngMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STRngMessage();
        int offset = 0;
        if (span.Length - offset < 4) return false;
        result.Value = BinaryPrimitives.ReadUInt32BigEndian(span.Slice(offset));
        offset += 4;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteBECore(Span<byte> span, STRngMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        if (span.Length - offset < 4) return false;
        BinaryPrimitives.WriteUInt32BigEndian(span.Slice(offset), value.Value);
        offset += 4;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STRngMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal static bool TryWrite(Span<byte> destination, STRngMessage value, out int bytesWritten)
    {
        return TryWriteCore(destination, value, out bytesWritten);
    }

    internal static bool TryReadBE(ReadOnlySpan<byte> span, out STRngMessage result, out int bytesRead)
    {
        return TryReadBECore(span, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Span<byte> destination, STRngMessage value, out int bytesWritten)
    {
        return TryWriteBECore(destination, value, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STRngMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[4];
        int n = stream.Read(buf);
        if (n < 4) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal static bool TryWrite(Stream stream, STRngMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[4];
        if (!TryWriteCore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

    internal static bool TryReadBE(Stream stream, out STRngMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[4];
        int n = stream.Read(buf);
        if (n < 4) { result = null; bytesRead = n; return false; }
        return TryReadBECore(buf, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Stream stream, STRngMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[4];
        if (!TryWriteBECore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STMacMessage
{
    internal const int SizeOfStruct = 6;

    internal byte[] Address { get; set; }

    private static bool TryReadCore(ReadOnlySpan<byte> span, out STMacMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STMacMessage();
        int offset = 0;
        {
            var _arr_Address = new byte[6];
            for (int i = 0; i < 6; i++)
            {
                if (span.Length - offset < 1) return false;
                _arr_Address[i] = span[offset];
                offset += 1;
            }
            result.Address = _arr_Address;
        }
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteCore(Span<byte> span, STMacMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        {
            int _count_Address = value.Address != null ? Math.Min(value.Address.Length, 6) : 0;
            for (int i = 0; i < _count_Address; i++)
            {
                if (span.Length - offset < 1) return false;
                span[offset] = value.Address[i];
                offset += 1;
            }
            for (int i = _count_Address; i < 6; i++)
            {
                if (span.Length - offset < 1) return false;
                span[offset] = (byte)0;
                offset += 1;
            }
        }
        bytesWritten = offset;
        return true;
    }

    private static bool TryReadBECore(ReadOnlySpan<byte> span, out STMacMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STMacMessage();
        int offset = 0;
        {
            var _arr_Address = new byte[6];
            for (int i = 0; i < 6; i++)
            {
                if (span.Length - offset < 1) return false;
                _arr_Address[i] = span[offset];
                offset += 1;
            }
            result.Address = _arr_Address;
        }
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteBECore(Span<byte> span, STMacMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        {
            int _count_Address = value.Address != null ? Math.Min(value.Address.Length, 6) : 0;
            for (int i = 0; i < _count_Address; i++)
            {
                if (span.Length - offset < 1) return false;
                span[offset] = value.Address[i];
                offset += 1;
            }
            for (int i = _count_Address; i < 6; i++)
            {
                if (span.Length - offset < 1) return false;
                span[offset] = (byte)0;
                offset += 1;
            }
        }
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STMacMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal static bool TryWrite(Span<byte> destination, STMacMessage value, out int bytesWritten)
    {
        return TryWriteCore(destination, value, out bytesWritten);
    }

    internal static bool TryReadBE(ReadOnlySpan<byte> span, out STMacMessage result, out int bytesRead)
    {
        return TryReadBECore(span, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Span<byte> destination, STMacMessage value, out int bytesWritten)
    {
        return TryWriteBECore(destination, value, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STMacMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[6];
        int n = stream.Read(buf);
        if (n < 6) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal static bool TryWrite(Stream stream, STMacMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[6];
        if (!TryWriteCore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

    internal static bool TryReadBE(Stream stream, out STMacMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[6];
        int n = stream.Read(buf);
        if (n < 6) { result = null; bytesRead = n; return false; }
        return TryReadBECore(buf, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Stream stream, STMacMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[6];
        if (!TryWriteBECore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

partial class STNopMessage
{
    internal const int SizeOfStruct = 0;


    private static bool TryReadCore(ReadOnlySpan<byte> span, out STNopMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STNopMessage();
        int offset = 0;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteCore(Span<byte> span, STNopMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        bytesWritten = offset;
        return true;
    }

    private static bool TryReadBECore(ReadOnlySpan<byte> span, out STNopMessage result, out int bytesRead)
    {
        bytesRead = 0;
        result = new STNopMessage();
        int offset = 0;
        bytesRead = offset;
        return true;
    }

    private static bool TryWriteBECore(Span<byte> span, STNopMessage value, out int bytesWritten)
    {
        bytesWritten = 0;
        int offset = 0;
        bytesWritten = offset;
        return true;
    }

    internal static bool TryRead(ReadOnlySpan<byte> span, out STNopMessage result, out int bytesRead)
    {
        return TryReadCore(span, out result, out bytesRead);
    }

    internal static bool TryWrite(Span<byte> destination, STNopMessage value, out int bytesWritten)
    {
        return TryWriteCore(destination, value, out bytesWritten);
    }

    internal static bool TryReadBE(ReadOnlySpan<byte> span, out STNopMessage result, out int bytesRead)
    {
        return TryReadBECore(span, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Span<byte> destination, STNopMessage value, out int bytesWritten)
    {
        return TryWriteBECore(destination, value, out bytesWritten);
    }

    internal static bool TryRead(Stream stream, out STNopMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[0];
        int n = stream.Read(buf);
        if (n < 0) { result = null; bytesRead = n; return false; }
        return TryReadCore(buf, out result, out bytesRead);
    }

    internal static bool TryWrite(Stream stream, STNopMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[0];
        if (!TryWriteCore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

    internal static bool TryReadBE(Stream stream, out STNopMessage result, out int bytesRead)
    {
        Span<byte> buf = stackalloc byte[0];
        int n = stream.Read(buf);
        if (n < 0) { result = null; bytesRead = n; return false; }
        return TryReadBECore(buf, out result, out bytesRead);
    }

    internal static bool TryWriteBE(Stream stream, STNopMessage value, out int bytesWritten)
    {
        Span<byte> buf = stackalloc byte[0];
        if (!TryWriteBECore(buf, value, out bytesWritten)) return false;
        stream.Write(buf.Slice(0, bytesWritten));
        return true;
    }

}

#nullable restore